/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sulti.removecomentariosjavaclasses;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sul-Ti
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    private int Listar(File d) {
        int vTot = 0;
        int vLnDel = 0;
        //Lista Todos os Arquivos *.Java...
        for (File arq : d.listFiles()) {
            try {
                if (arq.isFile()) {
                    vLnDel = tratarClasse(arq);
                    vTot += vLnDel;
                } else if (arq.isDirectory()) {
                    vTot += Listar(arq);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return vTot;
    }

    private int tratarClasse(File f) throws IOException {
        int vLnDel = 0;
        //log.append(arq.getName().concat(System.lineSeparator()));
        log.append(f.getAbsolutePath().concat(System.lineSeparator()));
        //
        File tempFile = new File(f.getAbsolutePath().replace("JavaClassesOrigem", "JavaClassesDestino")); //+ ".temp"
        if (!tempFile.getParentFile().exists()) {
            tempFile.getParentFile().mkdir();
        }

        BufferedReader br;
        br = new BufferedReader(new FileReader(f));

        PrintWriter pw = new PrintWriter(new FileWriter(tempFile));
        String line = null;
        while ((line = br.readLine()) != null) {
            if (line.trim().startsWith("/**")) {
                vLnDel++;
            } else if (line.trim().startsWith("*")) {
                vLnDel++;
            } else if (line.trim().startsWith("*/")) {
                vLnDel++;
            } else {
                //if (!line.trim().equals(linhadelete)) {
                pw.println(line);
                pw.flush();
            }
        }
        pw.close();
        pw.flush();
        //if (!arq.delete()) {
        //    System.out.println("Arquivo não deletado!");
        //    return;
        //}
        //if (!tempFile.renameTo(arq)) {
        //    System.out.println("Arquivo renomeando!");
        //}
        log.append(f.getName().concat(" -> ").concat(String.valueOf(vLnDel)).concat(System.lineSeparator()));
        return vLnDel;
    }

    private void RemoveFullDir(File d) {
        if (d.isDirectory()) {
            File[] sun = d.listFiles();
            for (File toDelete : sun) {
                if (toDelete.isDirectory()) {
                    RemoveFullDir(toDelete);
                } else {
                    toDelete.delete();
                }
            }
        }
        d.delete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        btnProcessar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Diretório das Classes Java:");

        txtDir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDir.setText("C:\\Tmp\\JavaClassesOrigem\\");
            txtDir.setToolTipText("");

            btnProcessar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            btnProcessar.setText("Remover Comentários");
            btnProcessar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnProcessarActionPerformed(evt);
                }
            });

            log.setColumns(20);
            log.setRows(5);
            jScrollPane1.setViewportView(log);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setText("Log:");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)
                        .addComponent(txtDir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(btnProcessar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(3, 3, 3))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(0, 0, 0)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        // TODO add your handling code here:
        log.setText("");

        File dir = new File(txtDir.getText().trim());
        if (dir.exists() && dir.isDirectory()) {

            //Limpa o Destino antes de Iniciar!
            File tmpDir = new File(txtDir.getText().trim().replace("JavaClassesOrigem", "JavaClassesDestino"));
            if (tmpDir.exists()) {
                RemoveFullDir(tmpDir);
            }
            if (!tmpDir.exists()) {
                tmpDir.mkdir();
            }
            //
            int vTOTAL = Listar(dir);
            log.append("TOTAL".concat(" -> ").concat(String.valueOf(vTOTAL)).concat(System.lineSeparator()));
        }

    }//GEN-LAST:event_btnProcessarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JTextField txtDir;
    // End of variables declaration//GEN-END:variables
}
